### ISSUE TITLE
Animations referenced via "animation-name" are not transformed

### ISSUE THREAD

**Issue by patricknelson** [micantoine/svelte-preprocess-cssmodules#98]
I noticed that if I had `@keyframes dice {}` it would not work if referenced via `animation-name`, e.g.:

```css
.animate {
	animation-name: dice;
	animation-duration: 2s;
}
```

However, this still works:

```css
.animate {
	animation: dice 2s;
}
```

In the compiled output, `animation-name: dice 2s;` remains unmodified instead of being updated to `animation-name: dice-2BXUEF 2s;` (in my case). 

**Note:** This isn't a serious issue, since obviously `animation` still works, but figured it was worth reporting! 🙂
